export const postActionTypes = {
    FETCH_ALL_POSTS: 'FETCH_ALL_POSTS',
    FETCH_SINGLE_POST: 'FETCH_SINGLE_POST',
    UPLOAD_POST: 'CREATE_POST',
    UPDATE_POST: 'UPDATE_POST',
    DELETE_POST: 'DELETE_POST',
    LIKE_POST: 'LIKE_POST',
    DISLIKE_POST: 'DISLIKE_POST',
}

export const dialogContent = {
   DIALOG_ADD: "SNACKBAR_ADD",
}



